name: <script>alert('Hello');</script>
  
on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: test1
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
    - name: "</span><script>alert('Hello');</script><span>"
      env:
            MY_VAR: "\"</span><script>alert('Hello');</script><span>\""
      run: |
           echo $MY_VAR
           mkdir test
           whoami
           mount
           cat /home/runner/work/_actions/actions/first-interaction/v1/Dockerfile
           #echo "test" > /boot/a.txt
           ls -lash /boot/
    - name: Add comment
      uses: actions/github-script@v7
      with:
        script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: "\:\:after <script>alert('Hello');</script> \:\:before"
            })
